# Generated by Django 4.1.2 on 2022-10-27 19:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0002_alter_feed_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='like_authors',
            field=models.ManyToManyField(related_name='like_feeds', to=settings.AUTH_USER_MODEL),
        ),
    ]
